config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  get '/' => 'images#index'

  resources :users do
    resources :images do
      member do
        patch "like", to: "images#like"
      end
    end
  end

  resources :images do
    resources :comments, :except => [:show, :index]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
  validates :text, :presence => true
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  validates :description, :presence => true
  acts_as_votable


  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", large: "550x550>", xlarge: "1200x1200>" }
  #set image sizes before uploading images so it can reference url  i.e url(:large)

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :images
  has_many :comments
  acts_as_voter
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def user_admin
    if current_user
      if current_user.admin === true
        @user_admin = current_user
      end
    end
  end

  helper_method :user_admin

#add admin privelage

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :name, :password, :current_password, :avatar) }
  end

  #changes default route of devise to specific route after login
  def after_sign_in_path_for(user)
    user_path(user)
  end
  def after_update_path_for(user)
    user_path(user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # def index
  #   @comments = Comment.all
  # end

  # GET /comments/1
  # def show
  # end

  # GET /comments/new
  def new
    @image = Image.find(params[:image_id])
    @comment = @image.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @image = Image.find(params[:image_id])
    @comment = @image.comments.new(comment_params)
    if @comment.save
      flash[:notice] = 'Comment was successfully added.'
      respond_to do |format|
        format.html { redirect_to images_path  }
        format.js
      end
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:text).merge :user_id => current_user.id
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all.order(created_at: :desc)
    # @comment = Image.find(params[:id]).comments.new(comment_params)
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = current_user.images.build
  end

  def create
    @image = current_user.images.build(image_params)
    if @image.save
      flash[:notice] = "Upload successful!"
      redirect_to user_path(current_user)
    else

      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])

  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_path(current_user)
  end

  def like
    @image = Image.find(params[:id])
    current_user.likes @image
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

private
  def image_params
    params.require(:image).permit(:description, :image, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
  <%= render 'layouts/errors', :object => @comment %>

  <%= form_for [@image, @comment], remote: true do |f| %>
    <%= f.text_field :text, placeholder: "Add a comment...", autofocus: true %>
  <% end %>

app/views/comments/create.js.erb
$('form').remove();
$('#new_comment_link').show();
$('ul p').remove();
$('#image_comments').append('<%= @comment.text %>');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$('#new_comment_link').hide().after('<span id="comment-form"><%= j render("form") %></span>');

app/views/images/_form.html.erb
<%= render "layouts/errors", :object => @image %>

<%= form_for @image do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/images/edit.html.erb
<%= render 'form' %>

<p><%= link_to "Go back", user_path(current_user) %></p>

app/views/images/index.html.erb
<div class="home">
  <% if @images.any? %>
    <% @images.each do |image| %>
      <div class="row">
        <div class="home-scroll">

          <div class="home-avatar" id="<%= image.id %>">
            <%= image_tag image.user.avatar.url(:thumb), class:"round-image-50"%><span class="upload-time"><%= distance_of_time_in_words(image.created_at, Time.now) %> ago</span>
          </div>
          <%= image_tag image.image.url(:large), class: "each-img" %>

          <!-- how many likes -->
          <div id="like-count">
            <p><%= image.get_likes.size %> likes</p>
          </div>
          <!-- liked by who? -->
          <!-- <p><% image.votes_for.up.by_type(User).voters.each do |liked_by| %></p>
            <p><%= liked_by.name %></p>
          <% end %> -->

          <!-- username and caption -->
          <div class="description"><%= link_to image.user.name, user_path(image.user), class:'usernames'%> <%= image.description %></div>


          <!-- comments -->
          <ul id="image_comments">
            <% if image.comments.any? %>
              <% image.comments.each do |comment| %>
                <li><span class="usernames"><%= User.find(comment.user_id).name %></span> <%= comment.text %></li>
              <% end %>
            <% else %>
              <p>none yet!</p>
            <% end %>
          </ul>

          <hr>

          <!-- like/heart button -->
          <div class="heart-and-comment">


            <%= link_to like_user_image_path(image.user_id, image), method: :patch, id: "heart-link", remote: true do %>
              <i class="heart glyphicon glyphicon-heart-empty"></i>
            <% end %>


            <%= link_to "Add a comment...", new_image_comment_path(image), id: "new_comment_link", class: "btn comment-btn btn-default", remote: true %>

          </div>
        </div>
            <br><br><br>
      </div>
    <% end %>
  <% end %>
</div>

app/views/images/like.js.erb
$('#heart-link').remove();
$('.heart-and-comment').prepend('<j class="liked-heart glyphicon glyphicon-heart"></j>')
$('#like-count p').remove();
$('#like-count').append('<p><%= @image.get_likes.size %> likes</p>');

app/views/images/new.html.erb
<%= render 'form' %>

<p><%= link_to "Go back", images_path %></p>

app/views/images/show.html.erb
<%= image_tag @image.image.url(:large) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_menu.html.erb
<div class="blue collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">

      <div id="logo"><li><%= link_to "Oregram", '/' %></li></div>

    </ul>
    <ul class="white nav navbar-nav navbar-right">

        <% if current_user %>
          <li><%= link_to current_user.name, user_path(current_user) %> </li>

          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% if current_user.avatar == nil %>
            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
          <% end %>
        <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oregram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
</head>
<body>


<%= render "layouts/menu" %>


  <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>



</body>
</html>

app/views/users/show.html.erb
<h1><%= @user.name%>'s Page</h1>


<li><%= link_to 'Edit Profile',edit_user_registration_path(@user) %></li>



<h1>Uploaded Images</h1>


<ul class="images">

  <% @user.images.each do |image|%>
  <li class="crop">
        <%= image_tag image.image.url(:medium), class: "img-p"%>
      </li>

        <br>| <%= image.description %>
        <% if user_admin %>
          <%= link_to "Delete", image_path(image), class: "btn btn-xs btn-danger", method: :delete %>
          <%= link_to "Edit", edit_image_path(image), class: "btn btn-xs btn-primary" %>
        <% end  %>



  <% end %>
</ul>


<p><%= link_to "Upload", new_image_path %></p>